# Generated by Django 3.0.2 on 2020-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190705_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('', '-- choose a option --'), ('Size S', 'Size S'), ('Size M', 'Size M'), ('Size L', 'Size L'), ('Size XL', 'Size XL')], default='NA', max_length=20),
        ),
    ]
